### ISSUE TITLE
Add co-maintainer

### ISSUE THREAD

**Issue by menelaos** [zudov/purescript-var#11]
Hey @zudov, 
what do you think about adding a co-maintainer for this project?
That way at least the trivial PRs for `psc` changes could be merged more quickly. 
I'd be happy to help out but I guess someone from the core team (@paf31, @natefaubion, @garyb) would be even better ;-)

**Comment by zudov** [comment]
Hi. Yes, that would help.

I've invited all existing contributors (@menelaos, @natefaubion, @eskimor, @paf31) to have push access.

**Comment by menelaos** [comment]
Awesome, thanks!

**Comment by eskimor** [comment]
I feel honored, but I had to decline for now. As I am very busy right now with one of my projects and also not using purescript for the time being.
