### ISSUE TITLE
Replace methods with functions

### ISSUE THREAD

**Issue by texastoland** [zudov/purescript-var#6]
Since each class only has a specific instance, and require the newtypes for rows in instance heads, would it make sense to convert to simpler functions?

**Comment by zudov** [comment]
I believe you refer to `Updatable`, `Gettable`, `Settable`. I think their current purpose is to allow to make use of `get`/`set` both with `GettableVar`/`SettableVar` and normal `Var`, so overall we have following instances:

``` purescript
settableVar :: Settable eff (Var eff) a
settableSettableVar :: Settable eff (SettableVar eff) a

gettableVar :: Gettable eff (Var eff) a
gettableGettableVar :: Gettable eff (GettableVar eff) a

updatableVar :: Updatable eff (Var eff) a
```

But I don't like these excessive type-classes too much myself. Perhaps there is a better way here...
